### ISSUE TITLE
Typo in the README

### ISSUE THREAD

**Issue by blink1073** [gowravshekar/font-awesome-webpack#17]
The url used in the example in the README uses "minetype" instead of "mimetype".

**Comment by blink1073** [comment]
This is the one on npm: https://www.npmjs.com/package/font-awesome-webpack#usage

**Comment by SylvainCorlay** [comment]
This is crazy: https://github.com/search?q=minetype%3Dapplication%2Ffont-woff&type=Code&utf8=%E2%9C%93

**Comment by rgbkrk** [comment]
LMAO

This appears to have been fixed, there needs to be a patch release so developers copy pasta the right example.

**Comment by kevzettler** [comment]
+1

**Comment by williamboman** [comment]
![minetype-woff](https://cloud.githubusercontent.com/assets/6705160/19483395/78882e7c-9554-11e6-86a2-2a1b623005e1.jpg)

**Comment by wnordmann** [comment]
This typo is still present on npm 
https://www.npmjs.com/package/font-awesome-webpack

**Comment by wolfadex** [comment]
Readme is now correct on npm
